ci: use linux runners
Move the release workflow to Ubuntu so the build and publishing run faster.

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210936880542599?focus=true

diff --git a/.github/workflows/release_debug_version.yml b/.github/workflows/release_debug_version.yml
--- a/.github/workflows/release_debug_version.yml
+++ b/.github/workflows/release_debug_version.yml
@@ -7,24 +7,29 @@ on:
       - "v[0-9]+.[0-9]+.[0-9]+-dev"
 
 env:
-  PATH_TO_PROJECTS: ${{ github.workspace }}\src
-  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output\
+  PATH_TO_PROJECTS: ${{ github.workspace }}/src
+  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output/
   NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
   GITHUB_PACKAGES_URL: 'https://nuget.pkg.github.com/asv-soft/index.json'
+  PROPS_VERSION_VAR_NAME: 'ProductVersion'
 
 jobs:
   deploy:
     name: 'Deploy'
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     steps:
       - name: 'Checkout'
         uses: actions/checkout@v4
+
       - name: Setup .Net
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: |
             9.x.x
- 
+
+      - name: Add dotnet global tools folder to PATH
+        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
+
       - name: Set version variable
         env:
           TAG: ${{ github.ref_name }}
@@ -33,40 +38,53 @@ jobs:
           $newTag = $env:TAG
           $newTag = $newTag.TrimStart("v")
           echo "VERSION=$newTag" | Out-File -FilePath $env:GITHUB_ENV -Append
+          
+      - name: Read version from Directory.Build.props
+        id: read-version
+        run: |
+          version=$(grep -oP '<${{env.PROPS_VERSION_VAR_NAME}}>\K[^<]+' ./src/Directory.Build.props)
+          echo "PropsVersion=${version}" >> $GITHUB_ENV
+          
+      - name: Compare tag with NuGet package version
+        run: |
+          if [ "${{ env.PropsVersion }}" != "${{ env.VERSION }}" ]; then
+            echo "Error: Tag does not match NuGet package version"
+            exit 1
+          fi
 
       - name: Checking version
         run: echo ${{ env.VERSION }}
 
       - name: Setting the project version
         run: |
-          dotnet tool install -g dotnet-setversion    
-          setversion ${{ env.VERSION }} ${{ env.PATH_TO_PROJECTS }}\Asv.Mavlink\Asv.Mavlink.csproj    
-          
+          dotnet tool install -g dotnet-setversion
+          setversion ${{ env.VERSION }} ${{ env.PATH_TO_PROJECTS }}/Asv.Mavlink/Asv.Mavlink.csproj
+
       - name: Add NuGet source
         run: |
-          dotnet nuget add source ${{ env.GITHUB_PACKAGES_URL }} --username '${{ secrets.USER_NAME }}' --password '${{ secrets.GIHUB_NUGET_AUTH_TOKEN }}' --store-password-in-clear-text
+          dotnet nuget add source ${{ env.GITHUB_PACKAGES_URL }} --username "${{ secrets.USER_NAME }}" --password "${{ secrets.GIHUB_NUGET_AUTH_TOKEN }}" --store-password-in-clear-text
 
       - name: Restoring dependencies
         run: |
-          cd src    
-          dotnet restore    
+          cd src
+          dotnet restore
 
       - name: Building projects
         run: |
-          cd src    
-          dotnet build -c Release --no-restore    
-          
+          cd src
+          dotnet build -c Release --no-restore
+
       - name: Test projects
         run: |
           cd src
-          dotnet test 
+          dotnet test
 
       - name: Packing projects to Nuget
         run: |
-          cd src    
-          dotnet pack -c Release --no-build --no-restore -p:PackageVersion=${{ env.VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}    
+          cd src
+          dotnet pack -c Release --no-build --no-restore -p:PackageVersion=${{ env.VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
 
-      - name: Pushing packages to Github   
-        run: |    
-          cd src    
-          dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}Asv.Mavlink.${{ env.VERSION }}.nupkg -k ${{ secrets.GIHUB_NUGET_AUTH_TOKEN }} --skip-duplicate -s ${{ env.GITHUB_PACKAGES_URL }}
+      - name: Pushing packages to Github
+        run: |
+          cd src
+          dotnet nuget push "${{ env.PACKAGE_OUTPUT_DIRECTORY }}Asv.Mavlink.${{ env.VERSION }}.nupkg" -k "${{ secrets.GIHUB_NUGET_AUTH_TOKEN }}" --skip-duplicate -s ${{ env.GITHUB_PACKAGES_URL }}
